export default {
	template: `
        <section class="about-page">
            <main class="lorem-columns">
        
                <img class="dore-img" src="assets/img/dore.png" alt="" />
                <p>
                    All right, settle down. Settle down... Now, before I begin the lesson, will those of you who are playing in the match this afternoon move your clothes down onto the lower peg immediately after lunch, before you write your letter home, if you're not getting your hair cut, unless you've got a younger brother who is going out this weekend as the guest of another boy, in which case, collect his note before lunch, put it in your letter after you've had your hair cut, and make sure he moves your clothes down onto the lower peg for you. If a sperm is wasted God gets quite irate. I object to all this sex on the television. I mean, I keep falling off!
                </p>
                <p>
                    Why is it the world never remembered the name of Johann Gambolputty de von Ausfern-schplenden-schlitter-crasscrenbon-fried-digger-dangle-dongle-dungle-burstein-Von-knacker-thrasher-apple-banger-horowitz-ticolensic-grander-knotty-spelltinkle-grandlich-grumblemeyer-spelterwasser-kurstlich-himbleeisen-bahnwagen-gutenabend-bitte-ein-nürnburger-bratwurstle-gerspurten-mit-zwei-macheluber-hundsfut-gumberaber-shoenendanker-kalbsfleisch-mittler-aucher von Hautkopft of Ulm? Pero las llamas son peligrosas. Si usted ve una llama donde hay gente﻿ nadando, usted gritar: ¡Cuidado! ¡Llamas! We use only the finest baby frogs, dew picked and flown from Iraq, cleansed in finest quality spring water, lightly killed, and then sealed in a succulent Swiss quintuple smooth treble cream milk chocolate envelope and lovingly frosted with glucose. Hegel is arguing that the reality is merely an a priori adjunct of non-naturalistic ethics, Kant via the categorical imperative is holding that ontologically it exists only in the imagination, and Marx claims it was offside
                </p>
                <p>
                    This morning, shortly after 11:00, comedy struck this little house on Dibley Road. Sudden, violent comedy. We interrupt this program to annoy you and make things generally irritating. Well, er, yes Mr. Anchovy, but you see your report here says that you are an extremely dull person. You see, our experts describe you as an appallingly dull fellow, unimaginative, timid, lacking in initiative, spineless, easily dominated, no sense of humour, tedious company and irrepressibly drab and awful. And whereas in most professions these would be considerable drawbacks, in chartered accountancy, they're a positive boon.
                </p>
                <img class="yona-img" src="assets/img/yona.png" alt="" />
                <p>
                    Munch on tasty moths ask to be pet then attack owners hand so mice or find empty spot in cupboard and sleep all day pee in the shoe sleep nap at four in the morning wake up owner meeeeeeooww scratch at legs and beg for food then cry and yowl until they wake up at two pm jump on window and sleep while observing the bootyful cat next door that u really like but who already has a boyfriend end up making babies with her and let her move in. Poop on grasses. Pee in human's bed until he cleans the litter box there's a forty year old lady there let us feast for let me in let me out let me in let me out let me in let me out who broke this door anyway demand to have some of whatever the human is cooking, then sniff the offering and walk away or licks your face so curl into a furry donut. 
                </p>
                <!-- <img src="assets/img/goblin.jpeg"> -->
                <p>
                    Stare out the window yet wake up wander around the house making large amounts of noise jump on top of yona. Massacre a bird in the living room and then look like the cutest and most innocent animal on the planet so you're just gonna scroll by without saying meowdy?. Attack like a vicious monster purr while eating so get my claw stuck in the dog's ear. Your pillow is now my pet bed kitty power so cat walks in keyboard . My slave human didn't give me any food so i pooped on the floor crusty butthole hack up furballs and rub face on owner and cats are the world. Rub face on owner jump five feet high and sideways when a shadow moves swat at dog, or cry louder at reflection
                </p>
                <p>
                    ur human's bed and fall asleep again meow meow. If human is on laptop sit on the keyboard stand with legs in litter box, but poop outside. Sit by the fire when in doubt, wash. Behind the couch hiiiiiiiiii feed me now. Dead stare with ears cocked loves cheeseburgers spend all night ensuring people don't sleep sleep all day scoot butt on the rug. Drool. Why use post when this sofa is here spend six hours per day washing, but still have a crusty butthole but sit on the laptop for howl on top of tall thing yet refuse to drink water except out of someone's glass or immediately regret falling into bathtub. Sitting in a box chase little red dot someday it will be mine!. I shall purr myself to sleep scratch leg; meow for can opener to feed me. Sugar, my siamese, stalks me (in a good way), day and night flee in terror at cucumber discovered on floor. Climb a tree, wait for a fireman jump to fireman then scratch his face. Throw down all the stuff in the kitchen pee on walls it smells like breakfast yet attempt to leap between furniture but woefully miscalibrate and bellyflop onto the floor; what's your problem? i meant to do that now i shall wash myself intently i like big cats and i can not lie jump launch to pounce upon little yarn mouse, bare fangs at toy run hide in litter box until treats are fed i am the best, yet cat gets stuck in tree firefighters try to get cat down firefighters get stuck in tree cat eats firefighters' slippers. Stand in doorway, unwilling to chose whether to stay in or go out instantly break out into full speed gallop across the house for no reason purr like an angel toy mouse squeak roll over and kitty loves pigs and missing until dinner time. Lick face hiss at owner, pee a lot, and meow repeatedly scratch at fence purrrrrr eat muffins and poutine until owner comes back decide to want nothing to do with my owner today pounce on unsuspecting person yet annoy owner until he gives you food say meow repeatedly until belly rubs, feels good meowing chowing and wowing head nudges purr as loud as possible, be the most annoying cat that you can, and, knock everything off the table. Swat at dog if it fits, i sits so massacre a bird in the living room and then look like the cutest and most innocent animal on the planet. Terrorize the hundred-and-twenty-pound rottweiler and steal his bed, not sorry bite off human's toes so give me attention or face the wrath of my claws eat from dog's food. Meowing non stop for food rub against owner because nose is wet ask for petting, yet in the middle of the night i crawl onto your chest and purr gently to help you sleep. 
                </p>
            </main>
        </section>
    `
}
